name = "duyet-logs"
compatibility_date = "2025-10-01"
compatibility_flags = ["nodejs_compat", "nodejs_compat_populate_process_env"]
pages_build_output_dir = "dist"

# Analytics Engine Bindings
[[analytics_engine_datasets]]
binding = "CLAUDE_CODE_ANALYTICS"
dataset = "duyet_logs_claude_code_analytics"

[[analytics_engine_datasets]]
binding = "CLAUDE_CODE_LOGS"
dataset = "duyet_logs_claude_code_logs"

[[analytics_engine_datasets]]
binding = "CLAUDE_CODE_METRICS"
dataset = "duyet_logs_claude_code_metrics"

[[analytics_engine_datasets]]
binding = "GA_ANALYTICS"
dataset = "duyet_logs_ga_analytics"

[[analytics_engine_datasets]]
binding = "REALTIME_ANALYTICS"
dataset = "duyet_logs_realtime_analytics"

# Durable Object Bindings
# For Pages, the Durable Object is exported from functions/[[path]].ts
[[durable_objects.bindings]]
name = "REALTIME_AGGREGATOR"
class_name = "RealtimeAggregator"
script_name = "duyet-logs"

# D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "duyet-logs"
database_id = "1d875c4d-9e1c-4f96-99c1-08386c53670c"

# Environment Variables
[vars]
DATASET_CLAUDE_CODE_ANALYTICS = "duyet_logs_claude_code_analytics"
DATASET_CLAUDE_CODE_LOGS = "duyet_logs_claude_code_logs"
DATASET_CLAUDE_CODE_METRICS = "duyet_logs_claude_code_metrics"
DATASET_GA_ANALYTICS = "duyet_logs_ga_analytics"
DATASET_REALTIME_ANALYTICS = "duyet_logs_realtime_analytics"

# Note: Secrets for Analytics Insights API should be set via Cloudflare dashboard
# Pages projects don't support secrets_store_secrets in wrangler.toml
# Set CLOUDFLARE_ACCOUNT_ID and CLOUDFLARE_API_TOKEN as environment variables in the dashboard

[observability]
enabled = true

[placement]
mode = "smart"
